name: xiaoma
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.5
  dio: ^5.1.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_google_places: ^0.3.0
  flutter_typeahead: ^4.4.0
  flutter_mobx: ^2.0.6+5
  flutter_polyline_points: ^1.0.0
  flutter_svg: ^2.0.5
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  get_it: ^7.6.0
  google_maps_flutter: ^2.2.6
  image: ^4.0.17
  location: ^4.4.0
  mobx: ^2.1.3
  permission_handler: ^10.2.0
  pinput: ^2.2.31
  simple_ripple_animation: ^0.0.7
  sliding_up_panel: ^2.0.0+1
  shared_preferences: ^2.2.0
  package_info: ^2.0.2

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

  mobx_codegen: ^2.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/auth/
    - assets/splash/
    - assets/toasts/
    - assets/navs/
    - assets/home/
    - assets/image_2.png
    - assets/ring_2.png
    - assets/car-left.png
    - assets/car-right.png
    - assets/car-down.png
    - assets/maps/
    - assets/
    - .env

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Medium.ttf
        - asset: fonts/Poppins-Bold.ttf
        - asset: fonts/Poppins-Black.ttf
        - asset: fonts/Poppins-ExtraBold.ttf
        - asset: fonts/Poppins-Light.ttf
        - asset: fonts/Poppins-SemiBold.ttf
        - asset: fonts/Poppins-Thin.ttf
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages
